name: "File Compression & Extraction"
description: "A GitHub Action to compress or decompress files"
author: "YoungIn Kang"
inputs:
  action:
    description: "Specify 'compress' or 'decompress'"
    required: true
  format:
    description: "Compression format: 'zip', 'tar', or 'tar.gz'"
    required: true
  source:
    description: "Source file(s) or directories (comma-separated for multiple files)"
    required: true
  destination:
    description: "Destination file or directory"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "archive"
  color: "blue"
